[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
