[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
